### ISSUE TITLE
Nulls in AssessmentLocation column not allowing upload

### ISSUE THREAD

**Issue by KasperKittredge** [abtassociates/eva#284] opened 2023-06-16 19:29 UTC
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
I'm not sure if this is a 'bug' exactly, but we are unable to upload our exports to Eva because the 'AssessmentLocation' column in 'Assessments' is completely null. This is because this is an "Administrator-managed list of locations' that our communities (IA-501 and IA-502) decided not to utilize, so no clients have this completed in either of these CoCs. Is it possible to allow this column to be null in order to complete uploads to Eva?

**Comment by alex-silverman** [comment] 2023-06-20 19:50
Hi Kasper,

Thank you for the question. We have confirmed that Eva is working as intended and in accordance with the [HMIS CSV Specifications](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf) (see page 31). We will reach out to HUD to request a review of the requirement that this field cannot be null.

Alex

**Comment by alex-silverman** [comment] 2023-06-28 16:20
Hi Kasper,

I wanted to provide an update here: While these columns should not be null according to the [HMIS CSV Specifications](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf) (see page 31), we will adjust Eva by the end of the week to allow you to proceed, despite the nulls.

I will close this comment, but please submit a new one if anything else comes up.

Alex

**Closed by alex-silverman** 2023-06-28 16:20 UTC

**Comment by KasperKittredge** [comment] 2023-06-28 16:37
Thank you so much, Alex!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
