### ISSUE TITLE
Impermissible Character Update - 12/14/2023

### ISSUE THREAD

**Issue by LaurenBianchi** [abtassociates/eva#464] opened 2023-12-20 15:37 UTC
Hello and Happy Holidays! 

I saw in the change log there was a push on 12/14 changing how impermissible characters are checked/flagged during submissions. 
We are getting reports of some characters that are permitted (' and `) that are getting flagged as impermissible characters. 

I have submitted an [AAQ ](https://www.hudexchange.info/program-support/my-question/?askaquestionaction=public%3Amain.answer&key=5CE2B1DE-018C-4469-B0BF58FB2D528E60)to inquire about guidance for when there are responses that utilize characters with diacritical marks as they are not explicitly permitted but there is no further guidance on stripping/transforming the characters either. 

Is it possible for this flag to be a warning as opposed to an error in the interim so folks can push their csv through for DQ checks or would that cause the tool to crash again? 

Thank you for your time and insight,
LB

**Comment by alex-silverman** [comment] 2023-12-21 21:02
Hi Lauren,

We have heard this feedback from a few users, so we are going to, at least temporarily, not reject files due to these impermissible characters. Eva has been updated accordingly.

I will note, I'm surprised Eva flagged a normal apostrophe (') as one such character. right- and left-single quotation marks (` and ’), on the other hand, are intentionally flagged, as these can cause Eva to crash. Can you confirm that Eva was flagging normal apostrophes?

Alex

**Comment by LaurenBianchi** [comment] 2024-01-05 15:54
Hi, Alex! Just wanted to reach out - I am waiting for word back from the customer for report parameters/project IDs to confirm the reported issue.  My apologies for the delay.

**Comment by alex-silverman** [comment] 2024-01-07 17:10
No problem. Thank you for following up!

**Comment by LaurenBianchi** [comment] 2024-01-23 15:18
Hi @alex-silverman!
I am seeing some odd behaviors in the file structure analysis. 
These are the impermissible characters that are being flagged: 
![image](https://github.com/abtassociates/eva/assets/92442726/e89a91b5-5298-475e-b97c-e48e5142da80)

I have been reviewing the flagged lines within the CLS file and some are valid (i.e. "…"), but others are a bit less forward during review (i.e., " ,,,,,")

**Comment by alex-silverman** [comment] 2024-01-24 20:15
Hi Lauren,

So it does look like Eva is flagging commas, which is surprising. Especially because, as far as I can tell, there are no alternate "commas" like there are quotation marks. I'm curious what columns this is flagging. The detail about where the impermissible character is located should be included in Eva's File Structure Analysis (e.g. "Found impermissible character(s) in [FILE].csv, column [COLUMN], line [ROW]: [CHARACTER]"). Would you be able to screenshot a few rows of that output so I can see?

Alex

**Comment by LaurenBianchi** [comment] 2024-01-24 21:41
Hello, 
I used the character pulled directly and received the following in the converter: 
![image](https://github.com/abtassociates/eva/assets/92442726/bc60c633-7a49-4713-9101-0dba6f9893cb)

**Comment by alex-silverman** [comment] 2024-01-24 22:01
Oh my gosh, I'm being so silly. So Eva reports all impermissible characters within a given cell, separated by a comma. Based on your screenshots, I'm now guessing that the impermissible character is a non-breaking space, a non-ascii carriage return (U+21B5), or a zero-width non-breaking space character (U+FEFF). Can you try copying the characters *between* the commas or, better yet, the entire string into that converter and paste the Hex results into here?

**Comment by LaurenBianchi** [comment] 2024-01-24 22:22
From:
Found impermissible character(s) in CurrentLivingSituation.csv, column 13, line 770: 
, 
, 
, 
![image](https://github.com/abtassociates/eva/assets/92442726/a50268d2-a06a-4891-9712-6a2b44d2f673)

Can we allow these characters(non-breaking space, a non-ascii carriage return (U+21B5), or a zero-width non-breaking space character (U+FEFF))? Across the board from my experience from the data entry world - sys admin - vendor data analyst these are used often enough where transforming this data in the code veering from a SSOT would not be ideal and asking users to change how data is being entered/requesting them to fix is also not ideal. If this doesn't cause Eva to crash I would love to advocate for it to be accepted for data review.

**Comment by alex-silverman** [comment] 2024-01-25 00:29
Okay, so just to confirm, it does look like these are non-breaking spaces, zero-width spaces, and maybe non-ascii carriage returns. So at least we know what's happening!

I do appreciate your request for allowing these characters. This is why we made these "errors" rather than "High Priority", the latter of which would prevent you from using Eva. In this way, you can use Eva as normal, despite these issues. We do still recommend keeping to ASCII characters as these are more standardized across various platforms. And I should warn you that certain non-ASCII characters **can** cause problems for Eva. In our experience **right-single quotation marks have crashed Eva**, and these may be in 101 of your records, based on your first screenshot, though it's hard to say without seeing the character codes.

I hope this helps!

Given that we do still prefer ASCII characters but Eva should still allow many non-ASCII characters, I'm going to close this issue.

**Comment by LaurenBianchi** [comment] 2024-01-25 13:48
For reference purposes down the line if/when CSV Specifications are updated, I would like to note that the "`" character (ASCII Code 96/ Unicode U+0060) and spaces (which can be interpreted in my opinion to allow the characters we discussed yesterday) are permittable per the CSV Specifications.

**Comment by kiadso** [comment] 2024-01-25 20:04
Hi Lauren,

The Data Standards team has this on its agenda for the FY2026 specifications and we really appreciate your feedback and help in breaking this down. While the current specs do not explicitly name that the allowable characters are the ASCII versions of them all, I have confirmed that that was the intent.

Eva should not be flagging the backquote (`), nor should it be flagging ASCII spaces and any other ASCII characters. Just to confirm: is Eva flagging ASCII characters?

If Eva is flagging ASCII characters that are explicitly allowed, that is an issue we will work on right away. If not, this is a chance for the Data Standards team to reassess what standards are reasonable going forward and to define them clearly in FY 2026.

Thanks again for all your help with this, @LaurenBianchi!

**Comment by kiadso** [comment] 2024-01-30 14:20
Hi, I'm going to close this, but please re-open if you feel Eva is flagging any ascii characters that are allowed. In the meantime, the Errors that Eva is throwing will not cause anyone to lose the ability to use Eva.

Thanks again!

**Closed by kiadso** 2024-01-30 14:20 UTC
