### ISSUE TITLE
Nulls not allowed in this column causing rejection ....but there are no nulls

### ISSUE THREAD

**Issue by KSchlabachDHCD** [abtassociates/eva#150] opened 2023-01-12 21:39 UTC
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
My hashed uploads are being rejected by Eva with the error "The GrantID column in the Funder file contains nulls where they are not allowed. This could mean the column has an incorrect data type and was not imported or it could mean 1 or more values are null where they should not be."

**To Reproduce**
...

**Expected behavior**
I expected the hashed dataset to properly upload, as there are not any nulls in the GrantID column of the Funder.CSV. 
I tried to narrow down if a particular character in the GrantID column was causing this, so I ran hashed datasets for individual projects but the uploads are all accepted when I do that (so far grant IDs with a space, a dash, slash, and strings of only numeric values are all OK, as are the words "none" "NA" and "N/A"). Thinking perhaps it was only happening wen there were multiple projects combined I tried datasets with only projects that had been individually accepted (5 together) and that was rejected, but I tried again with only 3 of them and that was accepted. 

**Screenshots**
I attached the Funder.csv - it's been unzipped and opened by me, so date formatting issues are probably present, but they aren't with my zipped files.

**Desktop (please complete the following information):**
 - Operating System: Windows 10* 64-bit
 - Browser: Edge 108 on Windows 10
 - HMIS: VESTA by The Partnership Center

[Funder.csv](https://github.com/abtassociates/eva/files/10406222/Funder.csv)

**Comment by kiadso** [comment] 2023-01-17 16:08
Edited the GrantID and FunderOther columns to be not "High Priority" so that this vendor issue is not causing file rejections. 

It is still an error with the file, however, because GrantID should be data type character according to the specs, so even if the data from the HMIS is all numeric, it should be enclosed in quotes in all exports.

**Comment by santiagose** [comment] 2023-02-01 16:47
Hey everyone,

I am experiencing an issue where a GrantID column of the Funder file is being marked as having null values.  My understanding was that this error would no longer cause a rejection, can you investigate this for me, please? Below is the error found in the Structural Analysis File:

"The GrantID column in the Funder file contains nulls where they are not allowed. This could mean the column has an incorrect data type and was not imported or it could mean 1 or more values are null where they should not be."

Thanks!

**Comment by kiadso** [comment] 2023-02-01 16:50
Hi @santiagose 

Are you saying Eva is rejecting your file because of your GrantID column? Or you're seeing an "Error"?

**Comment by santiagose** [comment] 2023-02-01 16:51
Hi @kiadso It is a rejection.

**Comment by KSchlabachDHCD** [comment] 2023-02-01 16:52
Can I please be removed from this email chain? Thanks 😊

Kelly Schlabach
Pronouns: she, her, hers
HMIS Coordinator
Department of Housing and Community Development
O: (617) 573-1387

**Comment by kiadso** [comment] 2023-02-01 18:29
Hi @KSchlabachDHCD, you can unsubscribe from a thread by clicking the "unsubscribe" link in the email and you can control what emails you see more broadly in your GitHub account settings. Let me know if it's not working for you. 

@santiagose can you click "View it on GitHub" in your email and drag a screenshot of your File Structure Analysis report to your response here? (We can't seem to see your screenshots when you attach them to emails.)

Alternatively, you can just copy the entire content from your Excel download into your email response if that would be easier.

Thank you-

**Comment by santiagose** [comment] 2023-02-02 16:17
![Screenshot 2023-02-02 111651](https://user-images.githubusercontent.com/41306500/216380667-546931f6-77db-4839-9e3e-f325d12f627a.png)
Please see attached screenshot.

Thanks!

Sergio

**Comment by kiadso** [comment] 2023-02-02 16:56
Hi Sergio,

It looks like Eva is working as intended here. Are there other Issues in your file as well or is that the only one? If that is the only one, you should be getting a message once your upload is done that you have uploaded your file successfully. Eva will only reject your file if there is an issue where the "Type" column says "High Priority."

If you could send a screenshot that includes all the issues in your File Structure Analysis, that would be helpful. If that is the only one, and your export was uploaded successfully, then you should be able to continue on in Eva and see your data displayed in the other tabs. @santiagose

**Comment by santiagose** [comment] 2023-02-02 17:02
Hey,

I tried it again and it looks like its working :)

Thanks!

Sergio

**Closed** 2023-02-02 17:05 UTC
Labels: investigating
