### ISSUE TITLE
Enrollment Crosses Operating End

### ISSUE THREAD

**Issue by scampillo** [abtassociates/eva#457] opened 2023-12-07 17:20 UTC
System-level Data Quality
Enrollment Crosses Operating End

I am seeing this error - for about 50 clients:
FEMA COVID-19 | 822 | FEMA Non-Congregate Shelter - Health   Shelter D/Days Hotel-FK (inactive) | **Enrollment Crosses Operating End** | 49877 | 178280 | 2023-01-12

![image](https://github.com/abtassociates/eva/assets/142535880/763e4cc4-3a7f-4e9d-b9d7-ec5e605588be)
![image](https://github.com/abtassociates/eva/assets/142535880/92cca1f0-8302-4c90-9267-38c9bb17e8ab)

The client was exited on 10/06/2023 and program end date was 11/06/2023.

Can you let me know what I need to review for this error?  Thanks!

**Comment by kiadso** [comment] 2023-12-11 14:41
hi @scampillo,

Can you check your csv file for the following information?

- Open Enrollment.csv and search for the row with '178280' for the HouseholdID. Does it have anything in the DateDeleted column? If so, that's the problem, and it should be resolved Thursday at the latest, thanks to the other Issue you entered last week. If there is no DateDeleted, write down the value in the 'EnrollmentID' column. While you're here, you may want to also check for any other rows in this table where the PersonalID is '49877' and the ProjectID is '822.'
- Open Exit.csv and search for the row with the EnrollmentID you wrote down. If you cannot find it, that may mean there is another Enrollment that is maybe a duplicate and needs to be deleted. If you do find the EnrollmentID, please note the ExitDate and be sure it matches what you're seeing in your HMIS.

Let us know what you find!

Thank you, and if you need help with this, please let me know and we can set up a call.

-Eva Dev team

**Comment by scampillo** [comment] 2023-12-11 22:06
Enrollment.csv – 178280 DateDeleted Column is blank.
49877 – only one enrollment in project id 822.

Exit.csv – exit date 12/31/2022 (but this is for another program.)
I am not seeing an extit date for this program in the exit.csv.

The client has an exit:
***@***.***

Can we set up a time to review, and if I need to escalate to our vendor? I am open Tue, Wed afternoon, Thur morning and all day Friday (west coast time)

Thanks!

**Comment by kiadso** [comment] 2023-12-19 16:06
Hi @scampillo 
Thank you for diving into the csvs for this information. It's really helpful. I think since there is no Exit record for that EnrollmentID, that is why the issue is flagging for you. I can help you talk to your vendor about this, but not until January. Let me know if you'd like to set something up- you can email me at genelle_denzin at abtassoc dot com.

**Comment by kiadso** [comment] 2023-12-19 16:08
I'm going to close this, but please re-open if you want to discuss more here.

**Closed by kiadso** 2023-12-19 16:08 UTC
Labels: investigating, vendor issue
