### ISSUE TITLE
Eva crashed upon clicking "browse"

### ISSUE THREAD

**Issue by jessefjorstad** [abtassociates/eva#281] opened 2023-06-16 10:27 UTC
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
Site crash prior to upload

**To Reproduce**
1. Navigate to https://hmis.abtsites.com/eva/
2. Click Upload tab
3. Click "browse"
4. Chrome browser becomes unresponsive for several minutes then pop-up window says Eva had crashed

**Expected behavior**
1. Navigate to https://hmis.abtsites.com/eva/
2. Click Upload tab
3. Click "browse"
4. File explorer opens

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operating System: Windows 10 Enterprise
 - Browser: Chrome 114

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by alex-silverman** [comment] 2023-06-26 15:25
Could not reproduce and thus closing this issue.

**Closed by alex-silverman** 2023-06-26 15:25 UTC
