### ISSUE TITLE
Impermissible characters

### ISSUE THREAD

**Issue by scampillo** [abtassociates/eva#462] opened 2023-12-15 17:37 UTC
Hi starting today, I am seeing High Priority Error Impermissible characters

Found impermissible character(s) in CurrentLivingSituation.csv, column 13, line 1242: 
, 
Record: Located in TH at St. Mary's Center

Are apostrophe not allowed? Is this a vendor issue?

Thanks much!

**Comment by alex-silverman** [comment] 2023-12-19 15:09
We did push a recent change to catch and prevent uploads with impermissible characters, including "right single quotation" marks that look very similar to an apostrophe. These tricky characters can make it into the dataset if, for example, you copy and paste from Word. 

But the character you pasted in the issue is a comma, so I'm a little confused, as commas shouldn't be prevented. Did Eva flag a comma?

**Comment by alex-silverman** [comment] 2024-01-09 17:56
Closing this now. as we have been unable to replicate displaying commas for this flag. Please feel free to re-open or start a new issue if you continue encountering the problem.

**Closed by alex-silverman** 2024-01-09 17:56 UTC
