### ISSUE TITLE
Eva crashed while on System-level DQ Tab

### ISSUE THREAD

**Issue by jessefjorstad** [abtassociates/eva#282] opened 2023-06-16 10:30 UTC
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**

**To Reproduce**
1. Navigate to https://hmis.abtsites.com/eva/
2. Click Upload tab
3. Click "browse"
4. Upload "good" sample data
5. Click "Assess Data Quality"
6. Click "System-level"
7. Click "Top 10 Organizations"
8. "Eva has crashed" window appears

**Expected behavior**
7. Click "Top 10 Organizations"
8. Top 10 Organizations viz presents

**Screenshots**
![image](https://github.com/abtassociates/eva/assets/98542084/e2735462-0f5e-49da-857b-800c13b6aaa6)

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Chrome 114

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by alex-silverman** [comment] 2023-06-26 15:25
Could not reproduce and thus closing this issue.

**Closed by alex-silverman** 2023-06-26 15:25 UTC
